-- Canonical curriculum seed for VietStageApp hard-coded Đàn Tranh and Sáo Trúc data.
-- Idempotent: rerunning updates only records identified by stable lesson_code.
-- Requires current JPA schema: lessons.lesson_code, lesson_contents.payload_json and exercises.config_json.

BEGIN;

WITH source(lesson_code, instrument_name, local_level, sequence_index, display_number, title, description, teacher_text, practice_config) AS (
VALUES
  ('dan_tranh_level_1_bai_1_practice','Đàn Tranh',1,0,'1','Tìm hiểu nhạc cụ Đàn tranh','Xem video hướng dẫn lý thuyết nhạc lý, cấu tạo đàn tranh và tư thế ngồi, tư thế tay chuẩn.','Xem video hướng dẫn lý thuyết nhạc lý, cấu tạo đàn tranh và tư thế ngồi, tư thế tay chuẩn.','{"practiceMode":"note_sequence","noteSequence":[],"durations":[],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_1_bai_5_practice','Đàn Tranh',1,1,'2','Nhịp điệu cơ bản','Cô Mai giới thiệu trường độ: nốt trắng, nốt đen, nốt móc đơn và nốt móc kép.','','{"practiceMode":"note_sequence","noteSequence":[],"durations":[],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_1_bai_4_practice','Đàn Tranh',1,2,'3','Đọc bản nhạc cơ bản','Cô Mai giới thiệu âm vực 17 dây, tempo, khóa Sol, nhịp 4/4 và 2/4.','','{"practiceMode":"note_sequence","noteSequence":[],"durations":[],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_1_bai_8_practice','Đàn Tranh',1,3,'4.1','Kỹ thuật gảy ngón 2','Dùng ngón 2 gảy lần lượt 5 nốt trên 5 dây đầu: Sol1, La1, Đô2, Rê2 và Mi2. Ứng dụng nhận diện cao độ của từng dây bằng micro.','Hướng dẫn sử dụng ngón trỏ tay phải (ngón 2), giữ bàn tay khum tự nhiên và thả lỏng khi gảy đàn.','{"practiceMode":"note_sequence","noteSequence":["Sol1","La1","Đô2","Rê2","Mi2"],"durations":[1,1,1,1,2],"fingerings":["2","2","2","2","2"],"cues":[]}'),
  ('dan_tranh_level_1_bai_7_practice','Đàn Tranh',1,4,'4.2','Kỹ thuật gảy ngón 1','Dùng ngón 1 gảy lần lượt 5 nốt trên các dây 6 đến 10: Sol2, La2, Đô3, Rê3 và Mi3. Ứng dụng nhận diện cao độ của từng dây bằng micro.','Hướng dẫn sử dụng ngón cái tay phải (ngón 1), giữ cổ tay thả lỏng và gảy dây rõ tiếng.','{"practiceMode":"note_sequence","noteSequence":["Sol2","La2","Đô3","Rê3","Mi3"],"durations":[1,1,1,1,2],"fingerings":["1","1","1","1","1"],"cues":[]}'),
  ('dan_tranh_level_1_bai_9_practice','Đàn Tranh',1,5,'4.3','Kỹ thuật gảy ngón 3','Dùng ngón 3 gảy lần lượt 7 nốt trên các dây 11 đến 17: Sol3, La3, Đô4, Rê4, Mi4, Sol4 và La4. Ứng dụng nhận diện cao độ của từng dây bằng micro.','Hướng dẫn sử dụng ngón giữa tay phải (ngón 3), giữ bàn tay khum tự nhiên và gảy rõ tiếng ở âm vực cao.','{"practiceMode":"note_sequence","noteSequence":["Sol3","La3","Đô4","Rê4","Mi4","Sol4","La4"],"durations":[1,1,1,1,1,1,2],"fingerings":["3","3","3","3","3","3","3"],"cues":[]}'),
  ('dan_tranh_level_1_bai_2_practice','Đàn Tranh',1,6,'5','Luyện gảy các nốt cơ bản – Phần 1','Gảy lần lượt dây 1 đến dây 10: Sol1, La1, Đô2, Rê2, Mi2, Sol2, La2, Đô3, Rê3 và Mi3. Luân phiên ngón 2 rồi ngón 1 từ nốt đầu tiên. Ứng dụng dùng micro nhận diện đúng cao độ từng dây trước khi chuyển sang nốt tiếp theo.','Cách nhận diện cao độ 10 nốt nhạc cơ bản ở âm vực trầm và trung trên Đàn Tranh.','{"practiceMode":"note_sequence","noteSequence":["Sol1","La1","Đô2","Rê2","Mi2","Sol2","La2","Đô3","Rê3","Mi3"],"durations":[1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,2],"fingerings":["2","1","2","1","2","1","2","1","2","1"],"cues":[]}'),
  ('dan_tranh_level_1_bai_3_practice','Đàn Tranh',1,7,'6','Luyện gảy các nốt cơ bản – Phần 2','Gảy lần lượt dây 11 đến dây 17: Sol3, La3, Đô4, Rê4, Mi4, Sol4 và La4. Luân phiên ngón 3, ngón 2 rồi ngón 1 từ nốt đầu tiên. Ứng dụng dùng micro nhận diện đúng cao độ từng dây trước khi chuyển sang nốt tiếp theo.','Cách nhận diện cao độ 7 nốt nhạc ở âm vực cao trên Đàn Tranh.','{"practiceMode":"note_sequence","noteSequence":["Sol3","La3","Đô4","Rê4","Mi4","Sol4","La4"],"durations":[1.5,1.5,1.5,1.5,1.5,1.5,2],"fingerings":["3","2","1","3","2","1","3"],"cues":[]}'),
  ('dan_tranh_level_2_bai_10_practice','Đàn Tranh',1,8,'7','Luyện bài Lý cây đa – Nửa đoạn đầu','Luyện gảy đoạn đầu bài Lý Cây Đa với nhịp độ chậm.','Hướng dẫn gảy đoạn đầu bài Lý Cây Đa: giai điệu và ngón gảy.','{"practiceMode":"note_sequence","noteSequence":["Sol2","Sol2","La2","Đô3","Rê3","Mi3","Rê3","Đô3","La2","Sol2"],"durations":[1,1,0.5,0.5,1,1,0.5,0.5,1,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_2_bai_11_practice','Đàn Tranh',1,9,'8','Luyện bài Lý cây đa – Nửa đoạn cuối','Luyện gảy đoạn sau bài Lý Cây Đa.','Hướng dẫn gảy đoạn sau bài Lý Cây Đa.','{"practiceMode":"note_sequence","noteSequence":["La2","Đô3","Sol2","La2","Đô3","Rê3","Mi3","Rê3","Đô3","La2","Sol2","La2","Đô3","Sol2"],"durations":[0.5,0.5,1,0.5,0.5,1,1,0.5,0.5,1,0.5,0.5,0.5,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_2_bai_12_practice','Đàn Tranh',1,10,'9','Hoàn thiện bài Lý cây đa','Luyện đánh cả bài Lý Cây Đa với tiết tấu ổn định.','Ôn tập và ghép hoàn chỉnh bài Lý Cây Đa.','{"practiceMode":"note_sequence","noteSequence":["Sol2","Sol2","La2","Đô3","Rê3","Mi3","Rê3","Đô3","La2","Sol2","La2","Đô3","Sol2"],"durations":[1,1,0.5,0.5,1,1,0.5,0.5,1,1,0.5,0.5,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_7_bai_18_practice','Đàn Tranh',2,0,'10','Kỹ thuật Á','Thực hành Á xuống 6 dây từ dây 1 đến dây 6 và Á lên 6 dây từ dây 17 về dây 12.','','{"practiceMode":"glissando","rounds":[{"direction":"down","stringSequence":[1,2,3,4,5,6],"finger":"2"},{"direction":"up","stringSequence":[17,16,15,14,13,12],"finger":"1"}]}'),
  ('dan_tranh_level_7_bai_19_practice','Đàn Tranh',2,1,'11','Kỹ thuật nhấn','Gảy nốt gốc rồi nhấn đúng dây để nâng Mi lên Fa và La lên Si ở hai âm vực.','','{"practiceMode":"press","noteSequence":["Mi2","Fa2","La2","Si2","Mi3","Fa3","La3","Si3"],"techniqueCues":["press","","press","","press","","press",""]}'),
  ('dan_tranh_level_7_bai_20_practice','Đàn Tranh',2,2,'12','Kỹ thuật song thanh','Dùng ngón 1 và ngón 2 gảy đồng thời 2 dây để tạo song thanh.','','{"practiceMode":"double_stop","fingerings":["1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2"]}'),
  ('dan_tranh_level_7_bai_21_practice','Đàn Tranh',2,3,'13','Kỹ thuật rung dây','Gảy rồi rung lần lượt các nốt Sol2, La2, Đô3, Rê3, Mi3, Sol3 và La3 bằng tay trái.','','{"practiceMode":"vibrato","noteSequence":["Sol2","La2","Đô3","Rê3","Mi3","Sol3","La3"],"techniqueCues":["vibrato","vibrato","vibrato","vibrato","vibrato","vibrato","vibrato"]}'),
  ('dan_tranh_level_2_bai_13_practice','Đàn Tranh',2,4,'14','Luyện bài Sứ thanh hoa – Nửa đoạn đầu','Luyện gảy đoạn đầu bài Sứ Thanh Hoa ở tốc độ chậm.','Hướng dẫn gảy đoạn đầu bài Sứ Thanh Hoa: chuyển quãng và nhấn nhả nốt.','{"practiceMode":"note_sequence","noteSequence":["Rê3","Đô3","La2","Đô3","Đô3","La2","Đô3","Đô3","La2","Đô3","La2","Sol2"],"durations":[0.5,0.5,0.5,0.5,0.5,0.5,1,0.5,0.5,0.5,0.5,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_2_bai_14_practice','Đàn Tranh',2,5,'15','Luyện bài Sứ thanh hoa – Nửa đoạn cuối','Luyện gảy đoạn sau bài Sứ Thanh Hoa.','Hướng dẫn gảy đoạn sau bài Sứ Thanh Hoa.','{"practiceMode":"note_sequence","noteSequence":["Rê3","Đô3","La2","Đô3","Đô3","La2","Đô3","Đô3","Mi3","Rê3","Đô3","Sol2","La2","Mi3","Mi3","Rê3","Mi3","Rê3","Mi3","Sol3","Mi3"],"durations":[0.5,0.5,0.5,0.5,0.5,0.5,1,0.5,0.5,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_2_bai_15_practice','Đàn Tranh',2,6,'16','Hoàn thiện bài Sứ thanh hoa','Luyện đánh cả bài Sứ Thanh Hoa ở BPM 80 với các quãng rộng.','Ôn tập và ghép hoàn chỉnh bài Sứ Thanh Hoa.','{"practiceMode":"note_sequence","noteSequence":["Rê3","Đô3","La2","Đô3","Đô3","La2","Đô3","Đô3","La2","Đô3","La2","Sol2","Rê3","Đô3","La2","Đô3","Đô3","La2","Đô3","Đô3","Mi3","Rê3","Đô3","Sol2","La2","Mi3","Mi3","Rê3","Mi3","Rê3","Mi3","Sol3","Mi3","Rest","Mi3","Mi3","Rê3","Đô3","Mi3","Rê3","Rê3","Đô3","La2","Đô3","Đô3","La2","Đô3","La2","Sol2","Sol2","La2","Mi3","Sol3","Sol3","Mi3","Sol3","Sol3","Mi3","Rê3","Đô3","Đô3","Rê3","Đô3","Rê3","Mi3","Rê3","Rê3","Đô3","Rê3","Đô3","Rê3","Đô3","Đô3","La2","Đô3","Rê3","Rê3","Rê3"],"durations":[0.5,0.5,0.5,0.5,0.5,0.5,1,0.5,0.5,0.5,0.5,2,0.5,0.5,0.5,0.5,0.5,0.5,1,0.5,0.5,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,1,1,0.5,0.5,2,0.5,0.5,1,0.5,0.5,0.5,0.5,0.5,0.5,3,1,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_3_bai_7_practice','Đàn Tranh',3,0,'7','Luyện ngón tốc độ cao – Mã Vũ','Thực hành gảy bài nhạc Mã Vũ đoạn 1 đúng trường độ và nhịp độ nhanh.','Kỹ thuật giữ khung bàn tay vững chãi và di chuyển ngón nhanh trên các phím đàn khi chơi điệu hành khúc Mã Vũ.','{"practiceMode":"note_sequence","noteSequence":["Đô2","Rê2","Mi2","Rê2","Đô2","La2","Sol2","Sol2","Đô2","Rê2","Mi2","Sol2","Mi2","Rê2","Đô2","Đô2","La2","Sol2","Sol2","Sol2","Đô2","Rê2","Đô2","Sol2"],"durations":[0.5,0.5,1,0.5,0.5,1,0.5,0.5,1,0.5,0.5,1,0.5,0.5,1,0.5,0.5,1,0.5,0.5,1,0.5,0.5,1],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_4_bai_9_practice','Đàn Tranh',4,0,'9','Kỹ thuật nhấn Rung tay trái','Thực hành gảy các nốt ngân dài kết hợp nhấn rung đều tay trái.','Cách nhấn rung tay trái bên trái nhạn đàn để tạo âm ngân luyến truyền cảm, linh hồn Đàn Tranh.','{"practiceMode":"note_sequence","noteSequence":["Đô2","Đô2","Rê2","Rê2","Mi2","Mi2","Sol2","Sol2"],"durations":[2,2,2,2,2,2,2,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_5_bai_12_practice','Đàn Tranh',5,0,'12','Boss Stage – Thử thách sinh tồn','Chọn một bài đã học và biểu diễn bằng giao diện luyện tập hiện có.','','{"practiceMode":"note_sequence","noteSequence":["Sol1","La1","Đô2","Rê2","Mi2","Sol2","La2","Đô3","Rê3","Mi3","Sol3","La3","Đô4","Rê4","Mi4","Sol4","La4"],"durations":[],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_6_bai_17_practice','Đàn Tranh',6,0,'17','Bài 5: Chuyển hợp âm','Chuyển mượt mà giữa Đô trưởng (C) và La thứ (Am).','res://Video/DanBauDoan12Bai1.ogv','{"practiceMode":"note_sequence","noteSequence":["Đô2+Mi2+Sol2","La1+Đô2+Mi2","Đô2+Mi2+Sol2","La1+Đô2+Mi2","Đô2+Mi2+Sol2","La1+Đô2+Mi2","Đô2+Mi2+Sol2","La1+Đô2+Mi2","Đô2+Mi2+Sol2","La1+Đô2+Mi2","La1+Đô2+Mi2","Đô2+Mi2+Sol2","Đô2+Mi2+Sol2","La1+Đô2+Mi2"],"durations":[],"fingerings":["1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3"],"cues":["circle","circle","circle","circle","triangle","triangle","triangle","triangle","circle","circle","triangle","triangle","circle","triangle"]}'),
  ('dan_tranh_level_8_bai_30_practice','Đàn Tranh',7,0,'17','Kỹ thuật Vê','Thực hành kỹ thuật vê đều tay để tạo âm thanh liên tục và tròn tiếng.','','{"practiceMode":"tremolo","noteSequence":["Đô2","Mi2","Sol2","Mi2","Đô2","Mi2","Sol2","Mi2"],"fingerings":["2","2","2","2","2","2","2","2"]}'),
  ('dan_tranh_level_8_bai_31_practice','Đàn Tranh',7,1,'18','Hợp âm ba âm cơ bản','Phân biệt nốt đơn và hợp âm. Ôn lại các nốt cơ bản và gảy thử hợp âm Đô trưởng.','','{"practiceMode":"triad","fingerings":["1","2","1","2","1","1","1","2","1","2","1 + 2 + 3"]}'),
  ('dan_tranh_level_8_bai_32_practice','Đàn Tranh',7,2,'18.1','Hợp âm Đô trưởng','Thực hành đánh hợp âm Đô trưởng bằng ba ngón, giữ tiếng đàn rõ và đồng đều.','','{"practiceMode":"triad","fingerings":["1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3"]}'),
  ('dan_tranh_level_8_bai_33_practice','Đàn Tranh',7,3,'18.2','Hợp âm La thứ','Thực hành đánh hợp âm La thứ bằng ba ngón, giữ nhịp chắc và cân bằng các dây.','','{"practiceMode":"triad","fingerings":["1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3"]}'),
  ('sao_truc_level1_1_video','Sáo',1,0,'BÀI 1','Làm quen Sáo Trúc','Thực hành cầm sáo.','Cách cầm sáo trúc & lấy hơi.','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level1_1_video","localLevel":1,"video":"Cách cầm sáo trúc & lấy hơi.","practice":"Thực hành cầm sáo.","subtitles":[]}'),
  ('Node2','Sáo',2,1,'BÀI 1','Nốt Si (B4)','Thực hành nốt Si.','Hướng dẫn thổi nốt Si.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node2","localLevel":2,"video":"Hướng dẫn thổi nốt Si.","practice":"Thực hành nốt Si.","subtitles":[]}'),
  ('Node3','Sáo',2,2,'BÀI 2','Nốt La (A4)','Thực hành nốt La.','Hướng dẫn thổi nốt La.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node3","localLevel":2,"video":"Hướng dẫn thổi nốt La.","practice":"Thực hành nốt La.","subtitles":[]}'),
  ('Node4','Sáo',2,3,'BÀI 3','Nốt Sol (G4)','Thực hành nốt Sol.','Hướng dẫn thổi nốt Sol.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node4","localLevel":2,"video":"Hướng dẫn thổi nốt Sol.","practice":"Thực hành nốt Sol.","subtitles":[]}'),
  ('Node5','Sáo',2,4,'BÀI 4','Nốt Fa (F4)','Thực hành nốt Fa.','Hướng dẫn thổi nốt Fa.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node5","localLevel":2,"video":"Hướng dẫn thổi nốt Fa.","practice":"Thực hành nốt Fa.","subtitles":[]}'),
  ('Node6','Sáo',2,5,'BÀI 5','Nốt Mi (E4)','Thực hành nốt Mi.','Hướng dẫn thổi nốt Mi.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node6","localLevel":2,"video":"Hướng dẫn thổi nốt Mi.","practice":"Thực hành nốt Mi.","subtitles":[]}'),
  ('Node7','Sáo',2,6,'BÀI 6','Nốt Rê (D4)','Thực hành nốt Rê.','Hướng dẫn thổi nốt Rê.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node7","localLevel":2,"video":"Hướng dẫn thổi nốt Rê.","practice":"Thực hành nốt Rê.","subtitles":[]}'),
  ('Node8','Sáo',2,7,'BÀI 7','Nốt Đô (C4)','Thực hành nốt Đô.','Hướng dẫn thổi nốt Đô.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node8","localLevel":2,"video":"Hướng dẫn thổi nốt Đô.","practice":"Thực hành nốt Đô.","subtitles":[]}'),
  ('sao_truc_level3_1','Sáo',3,8,'BÀI 1','Khúc Nhạc Vui (Khung 1)','Khúc Nhạc Vui (Khung 1)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_1","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level3_2','Sáo',3,9,'BÀI 2','Khúc Nhạc Vui (Khung 2)','Khúc Nhạc Vui (Khung 2)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_2","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level3_3','Sáo',3,10,'BÀI 3','Khúc Nhạc Vui (Khung 3)','Khúc Nhạc Vui (Khung 3)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_3","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level3_4','Sáo',3,11,'BÀI 4','Khúc Nhạc Vui (Khung 4)','Khúc Nhạc Vui (Khung 4)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_4","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level3_5','Sáo',3,12,'BÀI 5','Khúc Nhạc Vui (Khung 5)','Khúc Nhạc Vui (Khung 5)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_5","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level3_6','Sáo',3,13,'BÀI 6','Khúc Nhạc Vui (Hoàn chỉnh)','Khúc Nhạc Vui (Hoàn chỉnh)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_6","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level4_1','Sáo',4,14,'BÀI 1','Inh Lả Ơi (Câu 1)','Inh Lả Ơi (Câu 1)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level4_1","localLevel":4,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level4_2','Sáo',4,15,'BÀI 2','Inh Lả Ơi (Câu 2)','Inh Lả Ơi (Câu 2)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level4_2","localLevel":4,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level4_3','Sáo',4,16,'BÀI 3','Inh Lả Ơi (Câu 3)','Inh Lả Ơi (Câu 3)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level4_3","localLevel":4,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level4_4','Sáo',4,17,'BÀI 4','Inh Lả Ơi (Câu 4)','Inh Lả Ơi (Câu 4)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level4_4","localLevel":4,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level4_5','Sáo',4,18,'BÀI 5','Inh Lả Ơi (Hoàn chỉnh)','Inh Lả Ơi (Hoàn chỉnh)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level4_5","localLevel":4,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_1','Sáo',5,19,'BÀI 1','Futari no Kimochi (Đoạn 1 - P1)','Futari no Kimochi (Đoạn 1 - P1)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_1","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_2','Sáo',5,20,'BÀI 2','Futari no Kimochi (Đoạn 1 - P2)','Futari no Kimochi (Đoạn 1 - P2)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_2","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_3','Sáo',5,21,'BÀI 3','Futari no Kimochi (Đoạn 1 - HC)','Futari no Kimochi (Đoạn 1 - HC)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_3","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_4','Sáo',5,22,'BÀI 4','Futari no Kimochi (Đoạn 2 - P1)','Futari no Kimochi (Đoạn 2 - P1)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_4","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_5','Sáo',5,23,'BÀI 5','Futari no Kimochi (Đoạn 2 - P2)','Futari no Kimochi (Đoạn 2 - P2)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_5","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_6','Sáo',5,24,'BÀI 6','Futari no Kimochi (Đoạn 2 - HC)','Futari no Kimochi (Đoạn 2 - HC)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_6","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_7','Sáo',5,25,'BÀI 7','Futari no Kimochi (Hoàn chỉnh toàn bài)','Futari no Kimochi (Hoàn chỉnh toàn bài)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_7","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('Node35','Sáo',6,26,'BÀI 1','Gặp Mẹ Trong Mơ (Khung 1)','Gặp Mẹ Trong Mơ (Khung 1)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node35","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node36','Sáo',6,27,'BÀI 2','Gặp Mẹ Trong Mơ (Khung 2)','Gặp Mẹ Trong Mơ (Khung 2)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node36","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node37','Sáo',6,28,'BÀI 3','Gặp Mẹ Trong Mơ (Khung 3)','Gặp Mẹ Trong Mơ (Khung 3)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node37","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node38','Sáo',6,29,'BÀI 4','Gặp Mẹ Trong Mơ (Khung 4)','Gặp Mẹ Trong Mơ (Khung 4)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node38","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node39','Sáo',6,30,'BÀI 5','Gặp Mẹ Trong Mơ (Khung 5)','Gặp Mẹ Trong Mơ (Khung 5)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node39","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node40','Sáo',6,31,'BÀI 6','Gặp Mẹ Trong Mơ (Khung 6)','Gặp Mẹ Trong Mơ (Khung 6)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node40","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node41','Sáo',6,32,'BÀI 7','Gặp Mẹ Trong Mơ (Khung 7)','Gặp Mẹ Trong Mơ (Khung 7)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node41","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node42','Sáo',6,33,'BÀI 8','Gặp Mẹ Trong Mơ (Hoàn chỉnh)','Gặp Mẹ Trong Mơ (Hoàn chỉnh)','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node42","localLevel":6,"video":"","practice":"","subtitles":[]}')
), prepared AS (
  SELECT s.*, i.id AS instrument_id,
    CASE
      WHEN s.instrument_name = 'Đàn Tranh' AND s.local_level = 1 THEN 1
      WHEN s.instrument_name = 'Đàn Tranh' AND s.local_level BETWEEN 2 AND 6 THEN 2
      WHEN s.instrument_name = 'Đàn Tranh' THEN 3
      WHEN s.instrument_name = 'Sáo' AND s.local_level <= 2 THEN 1
      WHEN s.instrument_name = 'Sáo' AND s.local_level <= 4 THEN 2
      ELSE 3
    END AS skill_level_order
  FROM source s JOIN instruments i ON i.name = s.instrument_name
), resolved AS (
  SELECT p.*, sl.skill_level_id AS skill_level_id, (SELECT u.user_id FROM users u JOIN roles r ON r.role_id=u.role_id WHERE r.role_name='INSTRUCTOR' ORDER BY u.user_id LIMIT 1) AS instructor_id
  FROM prepared p JOIN skill_levels sl ON sl.order_index=p.skill_level_order
)
INSERT INTO lessons (lesson_code, instrument_id, skill_level_id, created_by_user_id, title, description, approval_status, is_visible, order_index)
SELECT lesson_code, instrument_id, skill_level_id, instructor_id, title, description, 'APPROVED', true, sequence_index + 1
FROM resolved
ON CONFLICT (lesson_code) DO UPDATE SET
  instrument_id=EXCLUDED.instrument_id, skill_level_id=EXCLUDED.skill_level_id,
  title=EXCLUDED.title, description=EXCLUDED.description, approval_status='APPROVED', is_visible=true, order_index=EXCLUDED.order_index;

DELETE FROM lesson_contents c USING lessons l
WHERE c.lesson_id=l.lesson_id AND c.content_type='CURRICULUM_SEED'
  AND (l.lesson_code LIKE 'dan_tranh_%' OR l.lesson_code LIKE 'sao_truc_%' OR l.lesson_code LIKE 'Node%');

WITH source(lesson_code, display_number, teacher_text, practice_config) AS (VALUES
  ('dan_tranh_level_1_bai_1_practice','1','Xem video hướng dẫn lý thuyết nhạc lý, cấu tạo đàn tranh và tư thế ngồi, tư thế tay chuẩn.','{"practiceMode":"note_sequence","noteSequence":[],"durations":[],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_1_bai_5_practice','2','','{"practiceMode":"note_sequence","noteSequence":[],"durations":[],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_1_bai_4_practice','3','','{"practiceMode":"note_sequence","noteSequence":[],"durations":[],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_1_bai_8_practice','4.1','Hướng dẫn sử dụng ngón trỏ tay phải (ngón 2), giữ bàn tay khum tự nhiên và thả lỏng khi gảy đàn.','{"practiceMode":"note_sequence","noteSequence":["Sol1","La1","Đô2","Rê2","Mi2"],"durations":[1,1,1,1,2],"fingerings":["2","2","2","2","2"],"cues":[]}'),
  ('dan_tranh_level_1_bai_7_practice','4.2','Hướng dẫn sử dụng ngón cái tay phải (ngón 1), giữ cổ tay thả lỏng và gảy dây rõ tiếng.','{"practiceMode":"note_sequence","noteSequence":["Sol2","La2","Đô3","Rê3","Mi3"],"durations":[1,1,1,1,2],"fingerings":["1","1","1","1","1"],"cues":[]}'),
  ('dan_tranh_level_1_bai_9_practice','4.3','Hướng dẫn sử dụng ngón giữa tay phải (ngón 3), giữ bàn tay khum tự nhiên và gảy rõ tiếng ở âm vực cao.','{"practiceMode":"note_sequence","noteSequence":["Sol3","La3","Đô4","Rê4","Mi4","Sol4","La4"],"durations":[1,1,1,1,1,1,2],"fingerings":["3","3","3","3","3","3","3"],"cues":[]}'),
  ('dan_tranh_level_1_bai_2_practice','5','Cách nhận diện cao độ 10 nốt nhạc cơ bản ở âm vực trầm và trung trên Đàn Tranh.','{"practiceMode":"note_sequence","noteSequence":["Sol1","La1","Đô2","Rê2","Mi2","Sol2","La2","Đô3","Rê3","Mi3"],"durations":[1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,2],"fingerings":["2","1","2","1","2","1","2","1","2","1"],"cues":[]}'),
  ('dan_tranh_level_1_bai_3_practice','6','Cách nhận diện cao độ 7 nốt nhạc ở âm vực cao trên Đàn Tranh.','{"practiceMode":"note_sequence","noteSequence":["Sol3","La3","Đô4","Rê4","Mi4","Sol4","La4"],"durations":[1.5,1.5,1.5,1.5,1.5,1.5,2],"fingerings":["3","2","1","3","2","1","3"],"cues":[]}'),
  ('dan_tranh_level_2_bai_10_practice','7','Hướng dẫn gảy đoạn đầu bài Lý Cây Đa: giai điệu và ngón gảy.','{"practiceMode":"note_sequence","noteSequence":["Sol2","Sol2","La2","Đô3","Rê3","Mi3","Rê3","Đô3","La2","Sol2"],"durations":[1,1,0.5,0.5,1,1,0.5,0.5,1,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_2_bai_11_practice','8','Hướng dẫn gảy đoạn sau bài Lý Cây Đa.','{"practiceMode":"note_sequence","noteSequence":["La2","Đô3","Sol2","La2","Đô3","Rê3","Mi3","Rê3","Đô3","La2","Sol2","La2","Đô3","Sol2"],"durations":[0.5,0.5,1,0.5,0.5,1,1,0.5,0.5,1,0.5,0.5,0.5,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_2_bai_12_practice','9','Ôn tập và ghép hoàn chỉnh bài Lý Cây Đa.','{"practiceMode":"note_sequence","noteSequence":["Sol2","Sol2","La2","Đô3","Rê3","Mi3","Rê3","Đô3","La2","Sol2","La2","Đô3","Sol2"],"durations":[1,1,0.5,0.5,1,1,0.5,0.5,1,1,0.5,0.5,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_7_bai_18_practice','10','','{"practiceMode":"glissando","rounds":[{"direction":"down","stringSequence":[1,2,3,4,5,6],"finger":"2"},{"direction":"up","stringSequence":[17,16,15,14,13,12],"finger":"1"}]}'),
  ('dan_tranh_level_7_bai_19_practice','11','','{"practiceMode":"press","noteSequence":["Mi2","Fa2","La2","Si2","Mi3","Fa3","La3","Si3"],"techniqueCues":["press","","press","","press","","press",""]}'),
  ('dan_tranh_level_7_bai_20_practice','12','','{"practiceMode":"double_stop","fingerings":["1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2","1 + 2"]}'),
  ('dan_tranh_level_7_bai_21_practice','13','','{"practiceMode":"vibrato","noteSequence":["Sol2","La2","Đô3","Rê3","Mi3","Sol3","La3"],"techniqueCues":["vibrato","vibrato","vibrato","vibrato","vibrato","vibrato","vibrato"]}'),
  ('dan_tranh_level_2_bai_13_practice','14','Hướng dẫn gảy đoạn đầu bài Sứ Thanh Hoa: chuyển quãng và nhấn nhả nốt.','{"practiceMode":"note_sequence","noteSequence":["Rê3","Đô3","La2","Đô3","Đô3","La2","Đô3","Đô3","La2","Đô3","La2","Sol2"],"durations":[0.5,0.5,0.5,0.5,0.5,0.5,1,0.5,0.5,0.5,0.5,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_2_bai_14_practice','15','Hướng dẫn gảy đoạn sau bài Sứ Thanh Hoa.','{"practiceMode":"note_sequence","noteSequence":["Rê3","Đô3","La2","Đô3","Đô3","La2","Đô3","Đô3","Mi3","Rê3","Đô3","Sol2","La2","Mi3","Mi3","Rê3","Mi3","Rê3","Mi3","Sol3","Mi3"],"durations":[0.5,0.5,0.5,0.5,0.5,0.5,1,0.5,0.5,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_2_bai_15_practice','16','Ôn tập và ghép hoàn chỉnh bài Sứ Thanh Hoa.','{"practiceMode":"note_sequence","noteSequence":["Rê3","Đô3","La2","Đô3","Đô3","La2","Đô3","Đô3","La2","Đô3","La2","Sol2","Rê3","Đô3","La2","Đô3","Đô3","La2","Đô3","Đô3","Mi3","Rê3","Đô3","Sol2","La2","Mi3","Mi3","Rê3","Mi3","Rê3","Mi3","Sol3","Mi3","Rest","Mi3","Mi3","Rê3","Đô3","Mi3","Rê3","Rê3","Đô3","La2","Đô3","Đô3","La2","Đô3","La2","Sol2","Sol2","La2","Mi3","Sol3","Sol3","Mi3","Sol3","Sol3","Mi3","Rê3","Đô3","Đô3","Rê3","Đô3","Rê3","Mi3","Rê3","Rê3","Đô3","Rê3","Đô3","Rê3","Đô3","Đô3","La2","Đô3","Rê3","Rê3","Rê3"],"durations":[0.5,0.5,0.5,0.5,0.5,0.5,1,0.5,0.5,0.5,0.5,2,0.5,0.5,0.5,0.5,0.5,0.5,1,0.5,0.5,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,1,1,0.5,0.5,2,0.5,0.5,1,0.5,0.5,0.5,0.5,0.5,0.5,3,1,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_3_bai_7_practice','7','Kỹ thuật giữ khung bàn tay vững chãi và di chuyển ngón nhanh trên các phím đàn khi chơi điệu hành khúc Mã Vũ.','{"practiceMode":"note_sequence","noteSequence":["Đô2","Rê2","Mi2","Rê2","Đô2","La2","Sol2","Sol2","Đô2","Rê2","Mi2","Sol2","Mi2","Rê2","Đô2","Đô2","La2","Sol2","Sol2","Sol2","Đô2","Rê2","Đô2","Sol2"],"durations":[0.5,0.5,1,0.5,0.5,1,0.5,0.5,1,0.5,0.5,1,0.5,0.5,1,0.5,0.5,1,0.5,0.5,1,0.5,0.5,1],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_4_bai_9_practice','9','Cách nhấn rung tay trái bên trái nhạn đàn để tạo âm ngân luyến truyền cảm, linh hồn Đàn Tranh.','{"practiceMode":"note_sequence","noteSequence":["Đô2","Đô2","Rê2","Rê2","Mi2","Mi2","Sol2","Sol2"],"durations":[2,2,2,2,2,2,2,2],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_5_bai_12_practice','12','','{"practiceMode":"note_sequence","noteSequence":["Sol1","La1","Đô2","Rê2","Mi2","Sol2","La2","Đô3","Rê3","Mi3","Sol3","La3","Đô4","Rê4","Mi4","Sol4","La4"],"durations":[],"fingerings":[],"cues":[]}'),
  ('dan_tranh_level_6_bai_17_practice','17','res://Video/DanBauDoan12Bai1.ogv','{"practiceMode":"note_sequence","noteSequence":["Đô2+Mi2+Sol2","La1+Đô2+Mi2","Đô2+Mi2+Sol2","La1+Đô2+Mi2","Đô2+Mi2+Sol2","La1+Đô2+Mi2","Đô2+Mi2+Sol2","La1+Đô2+Mi2","Đô2+Mi2+Sol2","La1+Đô2+Mi2","La1+Đô2+Mi2","Đô2+Mi2+Sol2","Đô2+Mi2+Sol2","La1+Đô2+Mi2"],"durations":[],"fingerings":["1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3"],"cues":["circle","circle","circle","circle","triangle","triangle","triangle","triangle","circle","circle","triangle","triangle","circle","triangle"]}'),
  ('dan_tranh_level_8_bai_30_practice','17','','{"practiceMode":"tremolo","noteSequence":["Đô2","Mi2","Sol2","Mi2","Đô2","Mi2","Sol2","Mi2"],"fingerings":["2","2","2","2","2","2","2","2"]}'),
  ('dan_tranh_level_8_bai_31_practice','18','','{"practiceMode":"triad","fingerings":["1","2","1","2","1","1","1","2","1","2","1 + 2 + 3"]}'),
  ('dan_tranh_level_8_bai_32_practice','18.1','','{"practiceMode":"triad","fingerings":["1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3"]}'),
  ('dan_tranh_level_8_bai_33_practice','18.2','','{"practiceMode":"triad","fingerings":["1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3","1 + 2 + 3"]}'),
  ('sao_truc_level1_1_video','BÀI 1','Cách cầm sáo trúc & lấy hơi.','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level1_1_video","localLevel":1,"video":"Cách cầm sáo trúc & lấy hơi.","practice":"Thực hành cầm sáo.","subtitles":[]}'),
  ('Node2','BÀI 1','Hướng dẫn thổi nốt Si.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node2","localLevel":2,"video":"Hướng dẫn thổi nốt Si.","practice":"Thực hành nốt Si.","subtitles":[]}'),
  ('Node3','BÀI 2','Hướng dẫn thổi nốt La.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node3","localLevel":2,"video":"Hướng dẫn thổi nốt La.","practice":"Thực hành nốt La.","subtitles":[]}'),
  ('Node4','BÀI 3','Hướng dẫn thổi nốt Sol.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node4","localLevel":2,"video":"Hướng dẫn thổi nốt Sol.","practice":"Thực hành nốt Sol.","subtitles":[]}'),
  ('Node5','BÀI 4','Hướng dẫn thổi nốt Fa.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node5","localLevel":2,"video":"Hướng dẫn thổi nốt Fa.","practice":"Thực hành nốt Fa.","subtitles":[]}'),
  ('Node6','BÀI 5','Hướng dẫn thổi nốt Mi.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node6","localLevel":2,"video":"Hướng dẫn thổi nốt Mi.","practice":"Thực hành nốt Mi.","subtitles":[]}'),
  ('Node7','BÀI 6','Hướng dẫn thổi nốt Rê.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node7","localLevel":2,"video":"Hướng dẫn thổi nốt Rê.","practice":"Thực hành nốt Rê.","subtitles":[]}'),
  ('Node8','BÀI 7','Hướng dẫn thổi nốt Đô.','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node8","localLevel":2,"video":"Hướng dẫn thổi nốt Đô.","practice":"Thực hành nốt Đô.","subtitles":[]}'),
  ('sao_truc_level3_1','BÀI 1','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_1","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level3_2','BÀI 2','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_2","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level3_3','BÀI 3','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_3","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level3_4','BÀI 4','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_4","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level3_5','BÀI 5','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_5","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level3_6','BÀI 6','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level3_6","localLevel":3,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level4_1','BÀI 1','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level4_1","localLevel":4,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level4_2','BÀI 2','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level4_2","localLevel":4,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level4_3','BÀI 3','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level4_3","localLevel":4,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level4_4','BÀI 4','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level4_4","localLevel":4,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level4_5','BÀI 5','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level4_5","localLevel":4,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_1','BÀI 1','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_1","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_2','BÀI 2','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_2","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_3','BÀI 3','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_3","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_4','BÀI 4','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_4","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_5','BÀI 5','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_5","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_6','BÀI 6','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_6","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('sao_truc_level5_7','BÀI 7','','{"practiceMode":"sao_truc_pitch","stableNodeId":"sao_truc_level5_7","localLevel":5,"video":"","practice":"","subtitles":[]}'),
  ('Node35','BÀI 1','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node35","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node36','BÀI 2','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node36","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node37','BÀI 3','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node37","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node38','BÀI 4','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node38","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node39','BÀI 5','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node39","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node40','BÀI 6','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node40","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node41','BÀI 7','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node41","localLevel":6,"video":"","practice":"","subtitles":[]}'),
  ('Node42','BÀI 8','','{"practiceMode":"sao_truc_pitch","stableNodeId":"Node42","localLevel":6,"video":"","practice":"","subtitles":[]}')
)
INSERT INTO lesson_contents (lesson_id, content_text, content_type, payload_json, schema_version, order_index)
SELECT l.lesson_id, NULLIF(s.teacher_text,''), 'CURRICULUM_SEED',
 json_build_object('schemaVersion',1,'displayNumber',s.display_number,'teacherText',s.teacher_text,'practiceConfig',s.practice_config::json)::text, '1', 1
FROM source s JOIN lessons l ON l.lesson_code=s.lesson_code;

INSERT INTO exercises (lesson_id, title, description, pass_threshold, order_index, exercise_type, practice_mode, config_json, schema_version)
SELECT l.lesson_id, 'Thực hành: ' || l.title, l.description, 60, 1, 'PRACTICE',
       COALESCE((c.payload_json::json->'practiceConfig'->>'practiceMode'),'note_sequence'),
       c.payload_json, '1'
FROM lessons l JOIN lesson_contents c ON c.lesson_id=l.lesson_id AND c.content_type='CURRICULUM_SEED'
WHERE NOT EXISTS (SELECT 1 FROM exercises e WHERE e.lesson_id=l.lesson_id AND e.order_index=1);

COMMIT;
