package com.example.vietstage_web_be.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXIST,
    EMAIL_NOT_FOUND,
    INVALID_PASSWORD,
    PASSWORD_INCORRECT,
    PASSWORD_NOT_MATCH,
    ROLE_NOT_FOUND,
    INVALID_ROLE,
    ACCOUNT_LOCKED,
    INVALID_VERIFICATION_CODE
}
